### DISCUSSION TITLE
Welcome to unifiprotect Discussions!

### DISCUSSION THREAD

**Discussion by briis** [briis/unifiprotect#153] [General]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

 You can use this forum to ask questions without opening an issue

**Comment by derhalbbrite** [comment]
Hi,
I have installed 0.7.0 version on my HA.
Now I tried to configurate it. But I could not find the form.

Where do I need to search for it?

Here are my HA specs:

Version | 2020.12.1
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.6
Operating System Family | Linux
Operating System Version | 5.4.79-v7l
CPU Architecture | armv7l
Timezone | Europe/Berlin

Thanks

**Reply by briis** [reply]
If I understand you correct, you have installed the Integration using HACS?
What that means is that you now have the files available in Home Assistant. Now you need to set it up. Please read this section and see if it does not help you: https://github.com/briis/unifiprotect#configuration

**Reply by derhalbbrite** [reply]
Hi,
yeah that is correct. I have installed it via HACS. 
Found my problem.
After installing the integration via HACS I did need to install it normaly in HA.

Thanks!

**Comment by adandl** [comment]
Hello Briis!
I'm still inspired by you when you just started to develop this integration - you make this look so easy but I know on the other hand that it is not :)
Question - is it possible to receive the images from the Unifi-Smart-Detection? That would give a nice overview who / what approached the home recently
Thanks a lot!

Albert

**Reply by briis** [reply]
Thank you Albert. And no this is not easy - I could not write 1 line of Python when I started, so I had a steep learning curve - but I also got a lot of help from the amazing community there is around HA. 

Hmmm, I have not seen a reference to the Smart Detection images in the API, but on the other hand, I havn't looked. Let me see if I can find something. Expect some delay, as I am on my way to a nice vacation. 😅

**Reply by adandl** [reply]
Enjoy your vacation and stay health!

**Reply by AngellusMortis** [reply]
@adandl I do have plans to get this working in a future version. It may be a way. I want the event thumbnails for my notifications as well.

**Reply by adandl** [reply]
This integration in general is amazing and works flawlessly.
Having notifications with thumbnails of who is at the front door is going to be exciting :)

Thank you!

**Reply by briis** [reply]
I am not absolutely sure how you are planning to detect if someone is at the Front Door, but here are two examples of HA Automations that will send you an image:

1.  If you have the UI Doorbell, the first automation will send you a notification with an image attached if someone rings the doorbell.
2. The second example sends an image if motion is detected on the Camera Outdoor.

You can read more about these Notifications in [this document](https://companion.home-assistant.io/docs/notifications/notification-attachments)

*mobile_app_in2023* is an android phone, but the same would work on IOS

The issue with UI Thumbnail, is that it does not get generated before sometime after the event has finished, so often an automation like below, will fail when trying to send the Thumbnail as image, as it is empty. Using the Camera snapshot function takes an image right away.

In the next release there will be a `unifiprotect_motion` event, that will trigger everytime motion is detected, that could then be used instead of the trigger in example 2.

```yaml
alias: Notify with Image when someone is ringing the Doorbell
description: ''
trigger:
  - platform: event
    event_type: unifiprotect_doorbell
condition: []
action:
  - service: camera.snapshot
    data:
      filename: /media/dorbell_latest.jpg
    target:
      entity_id: camera.dorbell
  - service: notify.mobile_app_in2023
    data:
      title: Someone is at the Front Door
      data:
        image: /media/local/dorbell_latest.jpg
      message: There is someone ringing the Front Door
mode: single
```

```yaml
alias: Notify with Image when motion detected outside
description: ''
trigger:
trigger:
  - platform: state
    entity_id: binary_sensor.motion_outdoor
    to: 'on'
condition: []
action:
  - service: camera.snapshot
    data:
      filename: /media/outdoor_latest.jpg
    target:
      entity_id: camera.outdoor
  - service: notify.mobile_app_in2023
    data:
      title: Motion detected
      data:
        image: /media/local/outdoor_latest.jpg
      message: There is someone moving around outside
