### DISCUSSION TITLE
DoorBell / Person Detection

### DISCUSSION THREAD

**Discussion by ericreich** [briis/unifiprotect#171] [Q&A]
Is there a way to create a switch for PersonDetection at like a doorbell camera?  I would use this for an Alexa routine to announce someone at the front door of all my Echo devices.

Thanks 
Eric Reich

**Comment by briis** [comment]
I am not familiar with Alexa, so not completely sure what you mean by switch. For me a switch is something that turns something on and off - and there is already a switch that enables or disables person detection created when you have the doorbell.

But I guess it is an automation that can ask Alexa to do something, when a person is detected you are looking for. 
Below is an example of an automation that sends a message using the service *Pushover* when a person is detected. You should be able to use that as a starting point, changing the trigger sensor to whatever name you have, and also the Action Service to notify through Alexa.

```yaml
alias: Send message when person detected
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.motion_dorklokke
    to: person
    attribute: event_object
condition: []
action:
  - service: notify.pushover
    data:
      message: A person has been detected on the Camera
mode: single
```
