### DISCUSSION TITLE
camera.play_stream doesn't work to Google hub/chromecast

### DISCUSSION THREAD

**Discussion by colmbuckley** [briis/unifiprotect#269] [Q&A]
Thanks for this excellent integration; it's exactly what I've been looking for. I have a G4 doorbell and am happily running a few useful automations using it.

One thing doesn't work, though - `camera.play_stream` won't display on any of my Google/Nest devices (eg: Chromecast with GoogleTV, Nest Home Hub, Nest Home Hub Max). The service doesn't report any errors, and the devices start the media player, but all I see on screen is the Cast logo, and it times out after a few seconds.

I can stream other camera entities (eg: Nest IQ cameras using the Nest integration), and I can view the RTSP stream from the G4 doorbell fine using VLC, so I'm not sure what's causing this. Are there any log files etc. I could use to start debugging? Any additional information I can send here?

Home Assistant OS: Core version core-2021.7.4, unifiprotect version 0.8.9.
Unifi Protect: Protect version 1.18.1 on UnifiOS 1.10.0.
G4 Doorbell: firmware version 4.38.1

Here's what I'm trying:
```
service: camera.play_stream
data:
  media_player: media_player.tv_room_tv
target:
  entity_id: camera.g4_doorbell_2
```

(`media_player.tv_room_tv` is a Chromecast with Google TV (Android TV), but I get the same result on a Home Hub and Home Hub Max).

Any ideas?

**Comment by briis** [comment]
I am not a cast expert, but I think the Nest Devices have an issue if the stream resolution is too high. If you go to the Unifi Protect Web App, and look at the RTSP Settings, try and turn off the 1600x1200 resolution, and turn on one of the others. Then reload the Unifi Protect Integration, and try again.

**Reply by colmbuckley** [reply]
Hmm, doesn't seem to be that; none of the three possible RTSP streams seem to work on any of the Google devices. The Nest cameras stream at 1080p and they seem to work fine.

My guess is that this is a limitation of Google Cast; it requires that the streamed data be available over HTTP/s rather than raw RTSP. Looking into whether there are any encapsulation options available, otherwise I'll see about wrapping it using VLC somehow.

**Reply by sbonnick** [reply]
Im currently looking into this too. It seems to be a problem with chromcast, as you mentioned. here is how others have done it with other RTSP sources in assistant:
https://www.reddit.com/r/homeassistant/comments/ameka9/rtsp_camera_to_chromecasts/

I havent yet tried this myself, but my thinking is seqencing these together.

**Comment by sbonnick** [comment]
So I was able to get this working as expected using a simple automation:
```
service: camera.play_stream
data:
  media_player: media_player.random_cast
target:
  entity_id: camera.g3_instant
```

For me the problem was the RTSP stream on my g3_instant were all turned off. turning on the low quality one, it started to work. I did need to reload the integration first. Once this was done, I no longer got the error any longer, and the video was seen on my chromecasts.

**Reply by colmbuckley** [reply]
Yes, this now suddenly works for me too (although I **swear** it didn't before); the main issue is that the HLS encapsulation of the RTSP stream which something somewhere is doing introduces about a 15-second delay. It's… not ideal.

At the moment, for things like "doorbell" events, I'm taking a JPG snapshot and casting **that** to the hubs, so that people can see who rang the doorbell.

**Reply by sbonnick** [reply]
nice, glad you got it working too. Ya I think the delay is due to the transcoding of the one stream to the other. I assume it also introduces some variance to in the delay base don when the closes "i frame" is in the stream as well... Anways. ya not ideal but works.

Do you have an example of how you are doing the screen shot? I was about to look at the same.

**Reply by colmbuckley** [reply]
Here's the automation I'm using to test; this might not be the final version:

```
alias: Doorbell Test
description: ''
trigger:
  - type: occupied
    platform: device
    device_id: XXXXXXX
    entity_id: binary_sensor.doorbell_g4_doorbell
    domain: binary_sensor
condition: []
action:
  - service: input_text.set_value
    target:
      entity_id: input_text.camera_timestamp
    data:
      value: '{{now().strftime("%H%M%S")}}'
  - service: camera.snapshot
    target:
      entity_id: camera.g4_doorbell_2
    data:
      filename: /config/www/camera/snap_{{states('input_text.camera_timestamp')}}.jpg
  - service: media_player.play_media
    target:
      entity_id: media_player.office_display
    data:
      media_content_id: >-
        http://192.168.1.20:8123/local/camera/snap_{{states('input_text.camera_timestamp')}}.jpg
      media_content_type: image/jpg
  - delay: '00:01:00'
  - service: media_player.media_stop
    target:
      entity_id: media_player.office_display
mode: single
```

Note the use of an `input_text` to make each camera snapshot filename unique - without this I found that I would sometimes see old (cached) versions of the image. I have a separate automation cleaning up old snapshots from the `/config/www/camera` directory.
