### DISCUSSION TITLE
Enable Logging for UniFi Protect Integration

### DISCUSSION THREAD

**Discussion by briis** [briis/unifiprotect#286] [General]
If you need to get more debug information for this Integration, add the following to the `configuration.yaml` file, which you find in your `config` directory:

```yaml
logger:
  default: error
  logs:
    custom_components.unifiprotect: debug
````
