### DISCUSSION TITLE
Doorbell Automation not operating since 1.20 update

### DISCUSSION THREAD

**Discussion by Urbanpixels** [briis/unifiprotect#446] [Q&A]
EDIT - Sorry, i made a mistake with capitalisation on the states, works fine now. Obviously need more coffee in a morning, i tried to delete this but no link to do so. Cheers! 

Good morning all. 

First of all i wanted to say thanks for this awesome integration it's really helped with a few things i was wanting to do in my Homeassistant.

Im struggling to get my Doorbell automation to run. In some update, not sure if it was the integration or HA the doorbell "push" used to be a state of OFF to ON but now i notice the doorbell is being triggered as Clear to Detected.

I've edited this in my automation but the doorbell never triggers it, It runs manually. Just not with the button press. Do you guys have any tips?

Below is my Automation:

`alias: Doorbell Chime - 23 Montgomery
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.front_doorbell_doorbell
    id: doorpress
    from: Clear
    to: Detected
condition:
  - condition: time
    after: '07:00:00'
    before: '19:30:00'
action:
  - service: media_player.play_media
    data:
      media_content_type: sound
      media_content_id: amzn_sfx_doorbell_chime_01
    target:
      entity_id:
        - media_player.living_room
        - media_player.office
        - media_player.kitchen
        - media_player.bedroom
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: notify.alexa_media
    data:
      message: Theres sombody at the front door.
      data:
        type: tts
      target:
        - media_player.living_room
        - media_player.office
        - media_player.kitchen
        - media_player.bedroom
mode: single
max: 3
`

**Comment by mikec83** [comment]
I am experiencing the same issue.

**Comment by AngellusMortis** [comment]
The HACS repo is deprecated. Please use the [official HA issue tracking](https://github.com/home-assistant/core/issues) for reporting issues.

Also, for @Urbanpixels "Clear" and "Detected" are not valid states for a binary sensor. It should be "on" or "off".

**Comment by mikec83** [comment]
@Urbanpixels I figured out the fix.  Here is an automations.yaml that works for my unifi protect doorbell to get my alexa to speak:

```
- id: doorbell
  alias: Detect Doorbell Pressed
  description: Notify User when the doorbell is pressed
  trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_doorbell
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      data:
        type: tts
      message: Ding Dong, Doorbell
      target:
      - media_player.office
      - media_player.kitchen
      - media_player.loft
  mode: single

```
