### ISSUE TITLE
Feature request:  Turn alerts on and off

### ISSUE THREAD

**Issue by samuprofe** [briis/unifiprotect#106]
I don't know if it would be possible to activate and deactivate the alerts from home assistant. Of course it would be very interesting to be able to activate them when you leave home and deactivate them when you enter, either through Wi-Fi tracking or through scenes that activate and deactivate other security components at the same time. (I know GPS traking is in UniFi Protect but this could be much more powerful)

Thank you for this great contribution to the community.

A greeting.

**Comment by briis** [comment]
Hi @samuprofe 
I need to understand a bit better what you want to do, as what you are describing above is a standard feature of Home Assistant. If you have a Device Tracker set up in HA, you can turn on/turn off a lot of things, when this device leaves the home or it is back at home. Personally I have two automations that do the following:
* **When I Leave my home**
  * It sets all my Cameras to record on Motion
  * Turns off all the lights
* **When I come back**
  * Sets all my Cameras to never record

Is it something like that you are looking for? Or else, please describe the scenario, and what it is you cannot already do. Thx.

/B

**Comment by samuprofe** [comment]
Hello,

Sorry, I didn't explain it well. My request is to be able to activate or deactivate the alerts in the UniFi Protect application (notification to the mobile phone and sending of email with photo when steel movement is detected with the indicated zones and sensitivity). However, I suppose I can do something similar from the home assist itself using the component's motion detector sensor. Does this sensor use the zones and sensitivity indicated in the Unifi Protect app?

Thank you so much.

**Comment by briis** [comment]
Everything relating to Zones and Sensitivity is better managed in the UI APP, but the motion sensor in HA is reflecting whatever you do there, as this just reacts to a Motion Event, that UI sends out. That event will only occur, if the values you set in zones and sensitivity are meet.
So try and see what you can do with automations in HA, and feel free to post here or in the HA Community if you need help.

**Comment by samuprofe** [comment]
I have already managed to send notifications from Home Assistant to my android mobile when movement is detected. On the other hand, could the photo of the movement detected be obtained to send it in the notification or in an email?

Thanks again.

**Comment by briis** [comment]
It depends a bit on what kind of notifier platform you use, if it supports images on not. But below you can find an example of an automation that is triggered when the Camera Motion sensor is activated. It hen takes a snapshot from the camera, and then sends it to my phone via the Notify Service Pushover.

You will need to modify this, but it can serve as inspiration.

```
- id: '1600074246635'
  alias: Send Snapshot when Camera Motion
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_camera_office
    to: 'on'
  condition: []
  action:
  - service: camera.snapshot
    data:
      entity_id: camera.camera_office
      filename: /local/office_snapshot.png
    entity_id: camera.camera_office
  - service: notify.pushover
    data:
      title: Motion on Office CAM
      message: Motion has been detected on your Office Camera. Please see attached
        picture
      data:
        attachment: /local/office_snapshot.png
  mode: restart
```
