### ISSUE TITLE
Doorbell defaults to pressed state in reboot of protect.

### ISSUE THREAD

**Issue by sebirdman** [briis/unifiprotect#121]
I've got some automations to notify us when the Doorbell is pressed. 

Tonight while updating the protect app, this automation triggered many times. 

Seems like the integration should be able to default to the unpressed state if no state is found. Or maybe delay the first read after reconnect?

**Comment by briis** [comment]
Is this a problem during daily operation or only when you do maintenance on the App?

**Comment by sebirdman** [comment]
@briis primarily during maintenance. I've also noticed that it happens when i do the "Reload" option on the unifi protect integration in home assistant.

**Comment by briis** [comment]
I am reluctant to change the detection routine as this has implications throughout the community. But to understand why this happens, could share one of the automations that gets triggered. So that I fully understand what you are listening for. I ask because I don't get this behaviour on my system at all. And I also have automations based on Doorbell press.

**Comment by sebirdman** [comment]
right now my trigger is just:

```
platform: state
entity_id: binary_sensor.doorbell_front_door
```

To listen for all state changes to the doorbell sensor

**Comment by sebirdman** [comment]
For anyone who's also hitting this, i've fixed it by specifying the state in my automation:

```
alias: Doorbell Pressed
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_front_door
    from: 'off'
    to: 'on'
condition: []
action:
  - service: script.turn_on
    entity_id: script.tts_whole_home
    data:
      variables:
        message: Someone is at the Front Door
  - data:
      title: Someone is at the Front Door
      message: Doorbell Pressed
    service: notify.mobile_app
  - service: notify.lg_webos_smart_tv
    data:
      message: Someone is at the Front Door
mode: single
```
