### ISSUE TITLE
Add sensor to count number of motion events for current day

### ISSUE THREAD

**Issue by briis** [briis/unifiprotect#14]
Add a sensor that display a counter with the number of motion events for the day.
Not sure exactly how to that yet, but could be trawling through the number of recordings.

**Comment by briis** [comment]
The implementation has been tested, and it works, but it requires to big a load and is too time consuming, that I will implement it.

**Comment by VinistoisR** [comment]
this is easily done with history_stats

**Comment by briis** [comment]
Could you show an example of how you would set that up in HA? Could be good to put in the documentation.

**Comment by VinistoisR** [comment]
Sure!

for example I have this in my configuration.yaml

```
sensor:
  - platform: history_stats
    name: Front Door Motion Events
    entity_id: binary_sensor.unifiprotect_motion_front_door
    state: 'on'
    type: count
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'
```
and I use a custom card to show the data:

```
animate: true
color_thresholds:
  - color: '#2ECC71'
    value: 0
  - color: '#F1C40F'
    value: 10
  - color: '#F39C12'
    value: 20
  - color: '#E67E22'
    value: 50
  - color: '#D35400'
    value: 100
entities:
  - entity: sensor.front_door_motion_events
group_by: date
hours_to_show: 168
icon: 'mdi:cctv'
show:
  fill: fade
  graph: bar
  icon: true
  state: true
type: 'custom:mini-graph-card'
```
or just a simple list that shows the counts:

```
type: entities
title: Camera Motion Events
entities:
  - entity: sensor.front_door_motion_events
```
