### ISSUE TITLE
Binary Sensor attributes event_length and event_score not consistently delivered with 0.6.4

### ISSUE THREAD

**Issue by TazUk** [briis/unifiprotect#146]
- HA Version: Core v0.118.4 run in Python3.8 venv
- Base OS: Ubuntu 18.04 LTS
- UnifiProtect Version: 0.6.4
- Last known UnifiProtect Version without issue: 0.6.4
- CloudKey+ G2 Firmware 1.1.13 Unifi Protect 1.13.7
- Cameras:
   - UVC-G3-AF
   - UVC-G4
   - UVC-G3-Flex
- Integration Options: 
   - Anonymous Snapshots not enabled
   - Scan interval 2 (default)

**Problem**
I use _event_length_ and _event_score_ attributes attached to the _binary_sensor_ entities to provide additional filtering for notifications - these are available when the _binary_sensor_ state changes to 'off'
With 0.6.4 installed these attributes are no longer reliably delivered and are sometimes delivered when the _binary_sensor_ is 'on' rather than off.
This can be observed with the sample automation via notifications, or monitored in real-time by triggering the motion sensor while observing the attributes in HA's Developer Tools States 

Reverting to 0.6.2 Unifi Protect resolves this issue.

**Sample Automation**
```
- id: unifiprotect_test
  alias: "UnifiProtect test"
  mode: queued
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_garden
      from: "off"
      to: "on"
    - platform: state
      entity_id: binary_sensor.motion_garden
      from: "on"
      to: "off"
  condition: []
  action:
    - service: notify.mobile
      data:
        title: "UnifiProtect Test"
        message: >
           Motion Sensor State: {{ states('binary_sensor.motion_garden') }}. <br>
           Score: {{ state_attr('binary_sensor.motion_garden', 'event_score') }}. <br>
           {% set time = (state_attr('binary_sensor.motion_garden', 'event_length') | int) %}
           {% set mins = ((time % 3600) / 60) | int %}
           {% set secs = time - (mins * 60) %}
           {% if time < 60 %}Length: {{ secs }} seconds
           {% else %}Length: {{ mins }} minutes {{ secs }} seconds
           {% endif %}

```

**Comment by briis** [comment]
My initial tests show that the event_score and length are actually updated, but it got out of sync with the on and off state. Just as an example, the below trigger will fire when the event_score is above 0. At that point in time there is also an event_length. Could just make a simple check for me if this is working at your sire also? 

This is not the solution, but just to verify you get the same behaviour.

```yaml
trigger:
  - platform: numeric_state
    entity_id: binary_sensor.motion_test_cam
    attribute: event_score
    above: '0'
```
