### ISSUE TITLE
Feature Request: Smart detect object classification sensor or attribute

### ISSUE THREAD

**Issue by jayscovill** [briis/unifiprotect#152]
Does Protect expose the type of object that was detected with Smart Detect via the API that this integration uses?

If so, is it possible to get that object type as a sensor or attribute of the motion binary sensor for a camera?

**Comment by briis** [comment]
Yes this is possible, and has been for a while. On each binary motion sensor, there is an attribute called `event_object`, if Smart Detect is enabled for that camera, the attribute will be updated with either *person* or *vehicle*.
Please note that after a little while the content will be reset, but you can use this in an automation as a trigger, like the below example. Hope this answers your question.

Example of trigger part for an automation, that triggers when a person is detected:

```yaml
platform: state
entity_id: binary_sensor.motion_dorklokke
to: person
attribute: event_object
```
