### ISSUE TITLE
[FR] set "Wide Dynamic Range"

### ISSUE THREAD

**Issue by freemann** [briis/unifiprotect#201]
My outside cams have some sun/shade/night issues and in the most ideally situation I want to set the "Wide Dynamic Range" setting based on daylight values.

Would it be possible to add a service which connects to the api endpoint at the WDR? 

Thanks for the great work, my doorbell was working in home assistant within 1min with your integration! And that for a just launch product. Loving it!

**Comment by briis** [comment]
Glad the Integration is useful and that it works for you.
I have not checked the API, but I do believe we should be able to create a service where you can set the value of WDR. Let me look in to it.

**Comment by briis** [comment]
I have just release v0.8.3 which gives you are new service to set the WDR value. (`unifiprotect.set_wdr_value`) The service takes two parameters: 
* The entity_id of the camera to perform the setting on
* An integer between 0 and 3 to set the WDR value. This is what Protect supports. Even though there is a slider in the App, when all the way to the left it is 0 and 3 all the way to the right.

Hope this was what you were looking for? You can check the the current value, by looking at the `wdr` attribute on the camera.

If this is what you wanted, please close the issue. Thx.

**Comment by freemann** [comment]
Thanks! Its working great!

The only thing is that I try to set the value dynamically by an action template and thats not working;
```Error while executing automation automation.set_doorbell_wdr: expected int for dictionary value @ data['value']```

This is my Action:
```
    - service: unifiprotect.set_wdr_value
      data:
        entity_id: camera.voordeur_bel
        value: >
          {% set wdr = 0|int %}
          {% if(states("sensor.period_of_day")|lower=='day') %}
            {% if((states("sensor.liveproduction")|int>100 and states("sensor.clearsky_current")|int>100)) %}
                {% if((states("input_number.pv_cloud_coverage")|int)<50) %}
                  {% set wdr = 2 %}
                {% else %}
                  {% set wdr = 3 %}
                {% endif %}         
            {% else %}
              {% set wdr = 1 %}
            {% endif %}
          {% elif(states("sensor.period_of_day")|lower=='night') %}
            {% set wdr = 0 %}
          {% elif(states("sensor.period_of_day")|lower=='morning' or states("sensor.period_of_day")|lower=='dusk') %}
            {% set wdr = 1 %}
          {% else %}
            {% set wdr = 1 %}
          {% endif %}
          {{wdr|int}}
```
Rendering the template in VSCode results at this moment in;
0

The variable is set as int and in the end casted as int and still the service is not accepting it.
Found this topic that it maybe is in a missing/incorrect service scheme.

Hoping you could help!

**Comment by briis** [comment]
For some reason I found that the entity_id sometimes needs to be added twice. What happens if you do like this:

```yaml
- alias: set_doorbell_wdr_x
  trigger:
    - platform: state
      entity_id: input_number.virtual_voordeur_bel_wdr
  action:
    - service: unifiprotect.set_wdr_value
      entity_id: camera.voordeur_bel
      data:
        entity_id: camera.voordeur_bel
        value: {{states('input_number.virtual_voordeur_bel_wdr')|int}}
```

**Comment by freemann** [comment]
Same error:
```Logger: homeassistant.components.automation.set_doorbell_wdr_x
Source: components/automation/__init__.py:416
Integration: Automatisering (documentation, issues)
First occurred: 6:45:28 (4 occurrences)
Last logged: 9:31:21

Error while executing automation automation.set_doorbell_wdr_x: expected int for dictionary value @ data['value']
```

6:45:28 was the transition from night to dusk, last logged is the time I triggered the modded automation;
```
- alias: set_doorbell_wdr_x
  trigger:
    - platform: state
      entity_id: input_number.virtual_voordeur_bel_wdr
  action:
    - service: unifiprotect.set_wdr_value
      entity_id: camera.voordeur_bel
      data:
        entity_id: camera.voordeur_bel
        value: "{{states('input_number.virtual_voordeur_bel_wdr')|int}}"
```

**Comment by briis** [comment]
I played around with this now in the development section, and I have the same problem. No matter what I do, this `value: "{{states('input_number.virtual_voordeur_bel_wdr')|int}}"` stays a string and as such the service fails. I searched the community and can't find a solution that is different from what you do.

The fix can be that I just expect a string instead, and then convert that to an integer when I need it.

**Comment by freemann** [comment]
Maybe its a HA bug or in some way intended behavior? 
Would the suggested workaround have any big/strange side effects for your project?  

If it's a simple "fix" for you, then yes please :)

**Comment by briis** [comment]
I thought it was a simple fix, but just tested it, and it still does not work - I just get a different error. I will play a bit more with it, and see if I can get it to work somehow.

**Comment by briis** [comment]
It actually seems that there is a bug with the new Service setup. If you use a value template as you do, it does not do anything, what I get in to the integration is this: `{{states('input_number.virtual_voordeur_bel_wdr')|int}}` and not the actual value, and that is why it fails. I will just test on a previous HA version, to see if your template works there.

**Comment by freemann** [comment]
OK, great to hear it's clear where this is coming from.  Hopefully it will be fixed soon :)

**Comment by freemann** [comment]
@briis whats the issue number on the HA repo where its discussed?

**Comment by briis** [comment]
> @briis whats the issue number on the HA repo where its discussed?
> Just update HA to 2021.3.1 and the template/automation is still failing.

I have not found or logged an issue on this as I wanted to do more tests, and I found that even when running this on version 2021.1.5 gives the same error.

I am right now not sure if it is this Integration, or a generic error with using templates in Services - I can only conclude that if you supply an integer the service works, but the template value does not get translated and/or converted.

**Comment by briis** [comment]
I am not sure why it does not work from the automation, but could you try and create a Script with the below, and then call that script as your Action, and see if that works?

```yaml
service: unifiprotect.set_wdr_value
data:
  entity_id: camera.voordeur_bel
  value: '{{ states("input_number.virtual_voordeur_bel_wdr") | int }}'
```
