### ISSUE TITLE
Binary sensor G4 Doorbell stopped working

### ISSUE THREAD

**Issue by mohlek** [briis/unifiprotect#208]
Hello,
I am running a UDM-Pro with Protect 1.18.0-beta1. 
Since the update the binary sensor for the doorbell stopped working. Everything else seems to be working fine.

**Comment by mohlek** [comment]
>DEBUG:pyunifiprotect.unifi_data:EVENT: DOORBELL IS RINGING
DEBUG:pyunifiprotect.unifi_protect_server:Procesed event: {'event_on': False, 'event_ring_on': True, 'event_type': 'ring', 'event_start': '2021-03-15 17:03:01', 'event_length': 1.0, 'event_score': 0, 'event_object': [], 'last_ring': '2021-03-15 17:03:01'}
INFO:__main__:Subscription: updated={'603d248e0010ef0387000556': {'event_start': '2021-03-15 17:03:01', 'event_score': 0, 'event_thumbnail': None, 'event_heatmap': None, 'event_on': False, 'event_ring_on': True, 'event_type': 'ring', 'event_length': 1.0, 'event_object': [], 'name': 'UVC G4 Doorbell', 'type': 'doorbell', 'model': 'UVC G4 Doorbell', 'mac': 'censored', 'ip_address': '192.168.1.37', 'firmware_version': '4.36.7', 'recording_mode': 'always', 'ir_mode': 'auto', 'status_light': False, 'rtsp': 'rtsp://192.168.1.1:7447/censored', 'up_since': '2021-03-10 15:05:22', 'online': True, 'has_highfps': True, 'has_hdr': True, 'video_mode': 'default', 'hdr_mode': True, 'mic_volume': 100, 'has_smartdetect': True, 'is_dark': False, 'privacy_on': False, 'has_opticalzoom': False, 'zoom_position': '0', 'wdr': '1', 'server_id': 'censored', 'last_motion': '2021-03-15 16:31:53', 'last_ring': '2021-03-15 17:03:01'}}
INFO:__main__:Subscription: updated={'603d248e0010ef0387000556': {'event_start': '2021-03-15 17:03:01', 'event_score': 0, 'event_thumbnail': None, 'event_heatmap': None, 'event_on': False, 'event_ring_on': False, 'event_type': 'ring', 'event_length': 1.0, 'event_object': [], 'name': 'UVC G4 Doorbell', 'type': 'doorbell', 'model': 'UVC G4 Doorbell', 'mac': 'censored', 'ip_address': '192.168.1.37', 'firmware_version': '4.36.7', 'recording_mode': 'always', 'ir_mode': 'auto', 'status_light': False, 'rtsp': 'rtsp://192.168.1.1:7447/censored', 'up_since': '2021-03-10 15:05:22', 'online': True, 'has_highfps': True, 'has_hdr': True, 'video_mode': 'default', 'hdr_mode': True, 'mic_volume': 100, 'has_smartdetect': True, 'is_dark': False, 'privacy_on': False, 'has_opticalzoom': False, 'zoom_position': '0', 'wdr': '1', 'server_id': 'censored', 'last_motion': '2021-03-15 16:31:53', 'last_ring': '2021-03-15 17:03:01'}}

Events did not change as far as I can tell

**Comment by briis** [comment]
Just to make sure: Are you talking about the doorbell motion sensor or the doorbell ring sensor?
It seems like it is the Ring Sensor. I have been running both 1.18.0-beta and now 1.18.0-beta4 and it is still working for me. 

When looking at this, you do get an `event_ring_on` equals True, which means the Ring Sensor should go to `on`
> DEBUG:pyunifiprotect.unifi_protect_server:Procesed event: {'event_on': False, 'event_ring_on': True,

**Comment by briis** [comment]
Could you share the automation that does not work?

**Comment by mohlek** [comment]
![image](https://user-images.githubusercontent.com/266946/111186475-5795b000-85b3-11eb-934b-26e472ff0d86.png)

The sensor is not updating in hass.

**Comment by mohlek** [comment]
This is my automation that worked before.

```yaml
alias: Türklingel
description: ''
trigger:
  - type: occupied
    platform: device
    device_id: 9a735c62154782ae6754b82eeb55485f
    entity_id: binary_sensor.doorbell_uvc_g4_doorbell
    domain: binary_sensor
condition: []
action:
  - service: camera.snapshot
    data:
      filename: www/tmp/cam_g4_doorbell.jpg
    entity_id: camera.uvc_g4_doorbell
  - service: notify.telegram_grp_shmohlek
    data:
      message: Jemand hat geklingelt.
      data:
        photo:
          file: www/tmp/cam_g4_doorbell.jpg
          caption: Jemand hat geklingelt.
mode: single
```

**Comment by briis** [comment]
Looking at the above picture the sensor is updating. It is only a very thin green line, and the last Tripped time is set to 17:03 today.

My trigger for this is a bit simpler than yours, I only have this:

```yaml
trigger:
  - platform: state
    entity_id: binary_sensor.doorbell_kamera_doerklokke
    to: 'on'
```
So I look for state instead of device, and then just check if state is set to on. Could you try that?
