### ISSUE TITLE
need help? no video in HomeKit?

### ISSUE THREAD

**Issue by ayocam** [briis/unifiprotect#242]
Is there something special I have to do to get the video streams to show up in HomeKit?  they show up in Home Assistant?

**Comment by briis** [comment]
I am not a homekit expert, but the below is what I have in my `configuration.yaml` file to add all my cameras to Homekit, and that works for me. The entity `camera.kamera_doerklokke` is a Doorbell, so that needs a bit extra config.

```yaml
homekit:
  filter:
    include_entity_globs:
      - camera.kamera_*
  entity_config:
      camera.kamera_doerklokke:
          linked_doorbell_sensor: binary_sensor.doorbell_kamera_doerklokke
          linked_motion_sensor: binary_sensor.motion_kamera_doerklokke
          support_audio: true
          video_codec: copy
```
