### ISSUE TITLE
Binary sensor values when automating?

### ISSUE THREAD

**Issue by proffalken** [briis/unifiprotect#281]
Hello, thanks for this integration, it's working brilliantly but I'm struggling with the automations.

I want an event to trigger inside the house when motion is detected on my G3 Flex cameras.

It looks like I should be able to do that by setting the following in my automation, however the automation never triggers.  What am I missing here?

```
trigger:
  - platform: state
    entity_id: binary_sensor.motion_driveway
    from: Clear
    to: Detected
    attribute: event_object
  condition: []
```
Are the values of the binary_sensor documented anywhere?

**Comment by andras-tim** [comment]
The state of a `binary_sensor` can be `on` or `off`. I think this is the problem.

(if you want to be sure, you can check the state changing with theb **Developer Tools / Events** tool)

**Comment by proffalken** [comment]
> The state of a `binary_sensor` can be `on` or `off`. I think this is the problem.
> 
> (if you want to be sure, you can check the state changing with the **Developer Tools / States** tool)
> 
> FYI: the shown `Clear` and `Detected` states are a translation of the binary states according to the current `device_class`.

Ah, ok, thanks, I'll give that a go - the developer tools were unclear as to the states that were being returned as well!

**Comment by proffalken** [comment]
FWIW, I've now got this running using two rules (one to turn the lights on, another to turn the lights off).

```
- id: '1629527411800'
  alias: Turn on lights when motion is detected on camera and it's after dark
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_driveway
    from: 'off'
    to: 'on'
  condition:
  - condition: sun
    before: sunrise
    after: sunset
  action:
  - type: turn_on
    device_id: f39f1abcde6f54e8b135f9ce5c8cc6bd
    entity_id: light.porch_light
    domain: light
    brightness_pct: 100
  mode: single
- id: '1629703052886'
  alias: Turn off porch light when no motion outside for > 10 minutes
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_driveway
    to: 'off'
    for: 00:10:00
  condition:
  - condition: sun
    after: sunset
    before: sunrise
  action:
  - type: turn_off
    device_id: f39f1abcde6f54e8b135f9ce5c8cc6bd
    entity_id: light.porch_light
    domain: light
  mode: single
```

This appears to be working well.
