### ISSUE TITLE
Use Cameras as day/night detection

### ISSUE THREAD

**Issue by christianreiss** [briis/unifiprotect#299]
Hey all,

I have several Bullet G3 scatered around my house. As I do shutter control, lights et all with homeassistant I took the usual "sun" state to close the covers when the sun was setting. But sometimes due to rainy conditions or even a clear sky the time to switch is never on the spot. Then it occured to me that the cameras have a very, very good attribute: is_dark. All cams turn on their IR when its "too dark" which is also spot-on for my taste. 

I have an automation that when two cams in the front _and_ two cams in the back turn their IR on (kind of a quorum) a bool its_day is set to false; during the morning another automation is setting the bool to true when the cams agree that it is day.

This works like a charm... but....

I am doing a trigger from camera.camera_garage (ie) and checking a change for the is_dark attribute. But even tho the attribute is correctly changing from true -> false and vice-versa, there is nothing triggered. A trace shows "no traces found".  The main state of the camera "recording" never changes, just the one yaml attribute. Is there a bug that this is not working? 

I am doing a time-pattern triggered condition, but that does not seem right (although working).

Thanks for any pointers!
-Chris.

**Comment by briis** [comment]
> I am doing a trigger from camera.camera_garage (ie) and checking a change for the is_dark attribute

Could you post the automation or script you are running? And also, is that specific camera part of the two front and two back cameras? 

> The main state of the camera "recording" never changes

Recording state only changes if you disable or enable it. If you set `recording_mode` to `never` it will turn to idle, else it will say recording. (Standard HA Feature)

**Comment by christianreiss** [comment]
```
alias: 'Sun: rising'
trigger:
  - platform: state
    entity_id: camera.garage
    attribute: is_dark
    from: true
    to: false
  - platform: state
    entity_id: camera.garden
    attribute: is_dark
    from: true
condition:
  - condition: state
    entity_id: camera.garden
    state: false
    attribute: is_dark
  - condition: state
    entity_id: camera.garage
    attribute: is_dark
  - condition: state
    entity_id: input_boolean.ist_hell
    state: 'off'
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.ist_hell
mode: single
```

Thats my auomation. I removed the time based trigger. Like this it would never get triggered.
