### ISSUE TITLE
Stream to Google Cast Error

### ISSUE THREAD

**Issue by osxaj** [briis/unifiprotect#308]
Hi.

I have the UniFi Protect integration working in Home Assistant, can see my cameras, see the seniors, etc. but when I setup an automation to announce someone and cast the particular camera based on the trigger (in my case for testing I toggle the cameras status light) my automation runs but when it gets to the step Camera: Play Steam I don't get the camera stream on my Google Home Hub device.  Error from the log:

Error while executing automation automation.google_hub_cast_test: camera.front_porch does not support play stream service

Is this a known issue/bug?

**Comment by osxaj** [comment]
That is the strange part, its an instant log entry so it does not seem to be timing out.  As soon as I trigger the automation the step to cast returns the error so it's like it's not even trying to obtain the stream itself.  Also confirmed this in Developer Tools, when I go to Services and setup the same automation action and hit Call Service I get the same error in my logs instantly.  

I can cast to these devices if I setup a generic camera in my config.ymal file with the minimal information, so it does not appear to be related to the play stream service itself.

```
camera:
  - platform: generic
    still_image_url: https://<IP ADDRESS TO STLL IMAGE>.jpg
    stream_source: rtsp://<IP ADDRESS TO G4 RTSP>
    name: Front_Porch_TestCam
    verify_ssl: false`
```

**Comment by AngellusMortis** [comment]
Another place to ask about for this is the discussions section on Github. There is a similar post there and a user was able to get it wokring:

https://github.com/briis/unifiprotect/discussions/269

**Comment by osxaj** [comment]
Thank you @AngellusMortis.  Your link above, plus your comment in that thread lead me down another path which works perfectly! In a nutshell I installed WebRTC, created an automation that calls webRTC.dashcast to the Google Home device.  The delay is literality non-existent (~1 second or less)! 

This will work in combination with the UniFi Protect HA app, just don't have that automation setup yet, was testing first.  My plan is when a UniFi "smart detection" is observed by UniFi Protect HA app it will cast that camera.  

```
  alias: Google Cast Test
  description: ''
  trigger:
  - platform: device
    type: turned_on
    device_id: 6781db756862e6b7bc25c3cdeb1c008b
    entity_id: switch.status_light_on_front_porch
    domain: switch
  condition: []
  action:
  - service: webrtc.dash_cast
    data:
      entity_id: media_player.office_display
      url: rtsp://<CAM_IP_ADDRESS>:7447/VxOriggwTluAdWwZ
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - service: media_player.turn_off
    target:
      entity_id: media_player.office_display
  mode: single
```

I also followed the suggestions in that thread using the UniFi 1280x720 RTSP stream, turning off all others for this camera. 

Thanks again for leading me towards a resolution which in turn allowed a better almost delay free solution.
