### ISSUE TITLE
Setting IR mode of camera as part of an automation

### ISSUE THREAD

**Issue by Calimerorulez** [briis/unifiprotect#455]
### New Feature

Sorry if it is already there and I have not found it, but could it be possible to set the IR mode of the camera as part of an automation?

Recent firmware update of my G3 Instant and my G4 Instant does not make my cameras auto switch to IR mode (no LEDs), because (as stated by the help I've got on the Ubiquiti forum) there are street lights in the view of the cameras.

Thus, it would be nice (if the Protect API supports it of course) to have the ability to set the IR mode via the HA integration.

Thank you for all your work!

**Comment by Calimerorulez** [comment]
Silly me, I've found it :)

**Comment by AngellusMortis** [comment]
Checkout the `select.select_option` service.

https://www.home-assistant.io/integrations/select/

Every doorbell has an Infrared mode select entity:

```
service: select.select_option
target:
  entity_id: select.front_doorbell_camera_infrared_mode
data:
  option: Always Disable
```
